env:
  _target_: boxforage.env.CoupledWrapper
  env:
    num_boxes: 2
    num_shades: 5
model:
  p_s:
    idxs: [[0, 1], [2]]
  p_o:
    idxs: [[0, 1], [2]]
train:
  init: {'mse_reg': 0.2}
  tune: {'mse_reg': 0.2}
