agent:
  env:
    _target_: 'boxforage.multi_box.SimpleBoxesForaging'
    spec:
      boxes:
        num_boxes: 2
        num_shades: 5
  env_param: [0.2, 0.05, 0.8, 10., -1., -0.5, 0.2]
  model:
    dist_config:
      state:
        idxs: [[0, 1], [2]]
      observation:
        idxs: [[0, 1], [2]]
    est_config:
      p_s:
        num_samples: 1000
        num_epochs: 2
        batch_size: 32
        optimizer:
          lr: 0.05
      p_s_o:
        num_samples: 10000
        num_epochs: 100
      p_o_s:
        num_samples: 10000
        num_epochs: 100
