agent:
  env:
    _target_: 'boxforage.single_box.SingleBoxForaging'
    spec:
      box:
        num_shades: 4
  env_param: [0.2, 0.8, 10.]
  model:
    est_config:
      p_s:
        num_samples: 1000
        num_epochs: 5
        batch_size: 64
        optimizer:
          lr: 0.05
